spring:
  application:
    name: marvel-test-one-spring-maven
    message: Welcome To marvel-test-one-spring-maven
server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
    health.show-details: "always"
